// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaRLP_vcY0xl5onP__1lx9AevObfui8zU',
    appId: '1:411536287353:web:210a3bb4ff9b0d83c616a8',
    messagingSenderId: '411536287353',
    projectId: 'bcg-staff-app',
    authDomain: 'bcg-staff-app.firebaseapp.com',
    databaseURL: 'https://bcg-staff-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bcg-staff-app.appspot.com',
    measurementId: 'G-T5W4XS3HKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4roZSeJapCCa7aN3WyPz0qEqpl0YwkJQ',
    appId: '1:411536287353:android:270c04f4a70724a8c616a8',
    messagingSenderId: '411536287353',
    projectId: 'bcg-staff-app',
    databaseURL: 'https://bcg-staff-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bcg-staff-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNi4kCghrGdBWwaWO_7q4YKCVOISDu61E',
    appId: '1:411536287353:ios:af812f2716217731c616a8',
    messagingSenderId: '411536287353',
    projectId: 'bcg-staff-app',
    databaseURL: 'https://bcg-staff-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bcg-staff-app.appspot.com',
    iosClientId: '411536287353-istfuuir9phfa5jroukg7q9ndj8n5ejk.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffPerformanceMapping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNi4kCghrGdBWwaWO_7q4YKCVOISDu61E',
    appId: '1:411536287353:ios:af812f2716217731c616a8',
    messagingSenderId: '411536287353',
    projectId: 'bcg-staff-app',
    databaseURL: 'https://bcg-staff-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bcg-staff-app.appspot.com',
    iosClientId: '411536287353-istfuuir9phfa5jroukg7q9ndj8n5ejk.apps.googleusercontent.com',
    iosBundleId: 'com.example.staffPerformanceMapping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaRLP_vcY0xl5onP__1lx9AevObfui8zU',
    appId: '1:411536287353:web:4eecdc8cec1373dbc616a8',
    messagingSenderId: '411536287353',
    projectId: 'bcg-staff-app',
    authDomain: 'bcg-staff-app.firebaseapp.com',
    databaseURL: 'https://bcg-staff-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bcg-staff-app.appspot.com',
    measurementId: 'G-1XESF9SSC9',
  );
}
